name: eusc_freaks
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.16.0
  cupertino_icons: ^1.0.2
  pocketbase: ^0.6.0
  flutter_hooks: ^0.18.5+1
  riverpod: ^2.1.3
  hooks_riverpod: ^2.1.3
  go_router: ^6.0.1
  fl_query: ^0.3.1
  fl_query_hooks: ^0.3.1
  adaptive_theme: ^3.1.1
  cached_network_image: ^3.2.3
  shared_preferences: ^2.0.15
  json_serializable: ^6.5.4
  json_annotation: ^4.7.0
  gap: ^2.0.1
  form_validator: ^2.1.1
  flutter_secure_storage: ^7.0.1
  timeago: ^3.3.0
  readmore: ^2.2.0
  flutter_dotenv: ^5.0.2
  visibility_detector: ^0.3.3
  flutter_native_splash: ^2.2.16
  file_picker: ^5.2.5
  http: ^0.13.5
  carousel_slider: ^4.2.1
  photo_view: ^0.14.0
  http_parser: ^4.0.2
  pdfx: ^2.3.0
  url_launcher: ^6.1.7
  flutter_cache_manager: ^3.3.0
  synchronized: ^3.0.1
  percent_indicator: ^4.2.2
  path_provider: ^2.0.11
  path: ^1.8.2
  open_filex: ^4.3.2
  auto_size_text: ^3.0.0
  expandable: ^5.0.1
  translator: ^0.1.7
  markdown_widget: ^2.0.0+1
  multi_select_flutter: ^4.1.3
  flutter_adaptive_scaffold: ^0.0.8
  badges: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.2.0
  flutter_launcher_icons: ^0.11.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - dev.env
    - prod.env

flutter_native_splash:
  color: '#000000'
  color_dark: '#000000'
  image: assets/logo_foreground.png
  image_dark: assets/logo_foreground.png
  android_12:
    color: '#000000'
    color_dark: '#000000'
    image: assets/logo_foreground.png
    image_dark: assets/logo_foreground.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/logo_foreground.png"
  remove_alpha_ios: true
  web:
    generate: true
    image_path: "assets/logo.png"
    background_color: "#000000"
    theme_color: "#ffffff"