// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPna1mtLKJe86E0Bb8dH3EfYU5ou3ac0Y',
    appId: '1:770997193899:web:03fb93db7588a8fa3abbee',
    messagingSenderId: '770997193899',
    projectId: 'eusc-freaks',
    authDomain: 'eusc-freaks.firebaseapp.com',
    storageBucket: 'eusc-freaks.appspot.com',
    measurementId: 'G-ZX4S87CT36',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpfVwwckGYVELaOwnH8pBuhgPmj2G-E_0',
    appId: '1:770997193899:android:a600124ee7da0b3d3abbee',
    messagingSenderId: '770997193899',
    projectId: 'eusc-freaks',
    storageBucket: 'eusc-freaks.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHlEax43Fu_NHzD2V6rOuvaIMGqDkkO7Y',
    appId: '1:770997193899:ios:cd44688845ffae863abbee',
    messagingSenderId: '770997193899',
    projectId: 'eusc-freaks',
    storageBucket: 'eusc-freaks.appspot.com',
    iosClientId: '770997193899-d9bpba417q918spfksqm3f8hefvuob3i.apps.googleusercontent.com',
    iosBundleId: 'dev.krtirtho.euscFreaks',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHlEax43Fu_NHzD2V6rOuvaIMGqDkkO7Y',
    appId: '1:770997193899:ios:cd44688845ffae863abbee',
    messagingSenderId: '770997193899',
    projectId: 'eusc-freaks',
    storageBucket: 'eusc-freaks.appspot.com',
    iosClientId: '770997193899-d9bpba417q918spfksqm3f8hefvuob3i.apps.googleusercontent.com',
    iosBundleId: 'dev.krtirtho.euscFreaks',
  );
}
