name: Development Build
on:
  push:
    branches:
      - build
  workflow_dispatch:

jobs:
  android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2.8.0
        with:
          cache: true
          channel: "stable"

      - name: Install dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y clang cmake ninja-build pkg-config libgtk-3-dev make python3-pip python3-setuptools patchelf desktop-file-utils libgdk-pixbuf2.0-dev fakeroot

      - name: Generate nightly version and Build APK
        run: |
          curl -sS https://webi.sh/yq | sh
          yq -i '.version |= sub("\+\d+", "-nightly-")' pubspec.yaml
          yq -i '.version += strenv(GITHUB_RUN_NUMBER)' pubspec.yaml
          echo '${{ secrets.PROD_ENV }}' > prod.env
          echo '${{ secrets.PROD_ENV }}' > dev.env
          flutter pub get
          flutter build apk
          mv build/app/outputs/apk/release/app-release.apk build/Eusc-freaks-all-arch.apk

      - name: Upload built apk
        uses: actions/upload-artifact@v2
        with:
          name: Android
          path: |
            build/Eusc-freaks-all-arch.apk

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.ACCESS_TOKEN }}
          file: build/Eusc-freaks-all-arch.apk
          asset_name: Eusc-freaks-all-arch.apk
          tag: refs/tags/v0.0.0
          overwrite: true
          body: Nightly build no. ${{ github.run_number }} of eusc-freaks
          

      - name: Setup upterm session (incase of failure)
        if: ${{ failure() }}
        uses: lhotari/action-upterm@v1
        with:
          limit-access-to-actor: true
